# Site settings
title: StaTEAstics
email: mkao006@gmail.com
description: A place where I record what I do at work and interesting involvements with statistics while I have my cup of Chinese tea.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mkao006.github.io" # the base hostname & protocol for your site
github_username:  mkao006
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
